name: deep_simulator
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.20
  - pip
  - pip:
      - pandas==1.5.3
      - nltk==3.7
      - networkx==3.0
      - numpy==1.24.2
      - scikit-learn==1.2.2
      - hyperopt==0.2.5
      - jellyfish==0.9.0
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorflow-io-gcs-filesystem==0.34.0
      - keras==2.11.0
      - prophet==1.1.1
      - opyenxes==0.3.0
      - pm4py==2.6.1
      - git+https://github.com/Mcamargo85/support_modules.git
      - gensim==4.3.1
      - seaborn==0.13.2
      - fitter==1.5.2
      - backports.zoneinfo==0.2.1
      - tzdata==2025.2
      - pyyaml==6.0